config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  resources :tags
  resources :users

  get '/admin-login', to: 'sessions#new'
  post '/admin-login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/about', to: 'pages#show'
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, { presence: true }

  has_many :taggings, dependent: :nullify
  has_many :tags, through: :taggings

  def tag_list
    self.tags.collect do |tag|
    tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings, :dependent => :destroy
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
  include BCrypt

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)

    redirect_to post_path(@post)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.password == params[:session][:password]
      session[:user_id] = @user.id
      redirect_to '/'
      p session
      p session[:user_id]
    else
      redirect_to admin_login_path
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    end
  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_params
    params.require(:post).permit(:title, :body, :tag_list)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Awesome Blog</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <div class="header">
        <h1>30 Projects Project</h1>
        <hr class="head-hr">
        <% if session[:user_id] %>
        <%= link_to "logout", logout_path%>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/show.html.erb
<%= link_to "Home", posts_path%>
<h1>About</h1>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

  <%= f.label :title %><br>
  <%= f.text_field :title %><br><br>

  <%= f.label :body %><br>
  <%= f.text_area :body %><br><br>

  <%= f.label :tag_list %><br>
  <%= f.text_field :tag_list %>

  <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<%= link_to "About the Project", about_path%>
</div>

<div class="clear"></div>
<div class="mini-nav">
  <h3>Edit Post</h3>
</div>
<% if session[:user_id] %>
  <%= render partial: 'form' %>
<% else %>
  <p>Only an Admin can do this - sorry!</p>
<% end %>

app/views/posts/index.html.erb
<%= link_to "About the Project", about_path%>
</div>

<div class="mini-nav">
  <h3>All Posts</h3> /
  <% if session[:user_id] %>
    <%= link_to "New Post", new_post_path%>
  <% end %>
</div>


<% @posts.each do |post| %>
  <h2> <%= link_to post.title, post_path(post), class: 'post_title'%> </h2>
  <p class='tagline'> Posted: <%= post.created_at.strftime("%m/%d/%Y | %I:%M%p") %> </p>
  <p> <%= post.body %> </p>

  <% post.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag), class: 'tag' %>
  <% end %>
  <hr>
<% end %>

app/views/posts/new.html.erb
<%= link_to "Home", posts_path%>
</div>
<div class="clear"></div>
<div class="mini-nav">
  <h3>Create a New Post</h3>
</div>

<% if session[:user_id] %>
  <%= render partial: 'form' %>
<% else %>
  <p>Only an Admin can do this - sorry!</p>
<% end %>

app/views/posts/show.html.erb
<%= link_to "About the Project", about_path%>
</div>
<div class="clear"></div>

<div class="mini-nav">
  <% if session[:user_id] %>
    <%= link_to "Edit", edit_post_path(@post), class: "post-edit" %> /
    <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Really delete the article?"}, class: "post-edit" %>
  <% end %>
</div>
<h2> <%= @post.title %> </h2>
<p> <%= @post.body %> </p>
<p> <% @post.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag), class: 'tag' %>
  <% end %></p>

app/views/tags/show.html.erb
<%= link_to "Home", posts_path%>
</div>
<div class="clear"></div>
<h2> Articles Under: <%= @tag.name %> </h2>
<p>
  <% @tag.posts.each do |post| %>
  <ul class = "articles">
    <li><%= link_to post.title, post_path(post) %></li>
  </ul>
  <% end %>
</p>

app/views/users/_login.erb
<%= form_for(@user) do |f| %>

  <%= f.label :username %><br>
  <%= f.text_field :username %><br><br>

  <%= f.label :email %><br>
  <%= f.text_field :email %><br><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %>

  <%= f.submit %>

<% end %>

app/views/users/new.erb
<%= link_to "Home", posts_path%>
</div>
<div class="clear"></div>
<div class="mini-nav">
  <h3>Create a new account</h3>
</div>
<%= render partial: 'login' %>